#!/usr/local/bin/python3
import sys
import subprocess

if len(sys.argv) < 1:
    print("Usage: gits <message>")
    sys.exit(1)

message = ""
for arg in sys.argv:
    message += arg + " "

subprocess.run(["git", "add", "."])
subprocess.run(["git", "commit", "-m", message])
subprocess.run(["git", "push"])