#!/usr/local/bin/python3
import sys, argparse
import subprocess as cmd

parser = argparse.ArgumentParser(description="Ez git push and setup")

parser.add_argument("message", help="Commit message", nargs="+")
parser.add_argument("-s", "--setup", help="Setup git, provide git repo to setup", nargs=1)

args = parser.parse_args()

if args.setup:
    cmd.run(["git", "init"])
    cmd.run(["git", "remote", "add", "origin", args.setup])
    cmd.run(["git", "push", "--set-upstream", "origin", "main"])
    
    quit()

elif args.message:
    message = ""
    for arg in args.message:
        message += arg + " "

    cmd.run(["git", "add", "."])
    cmd.run(["git", "commit", "-m", message])
    cmd.run(["git", "push"])
    
    quit()

else:
    print("Usage: gits <message>")
    quit()