#!/usr/local/bin/python3
import sys, os

if os.path.exists("makefile"):
	print("makefile already exists")
	sys.exit(1)

if len(sys.argv) > 1:
	match sys.argv[1]:
		case "rust":
			open("makefile", "w").write(
"""
all:
	cargo run

test:
	@cargo test

check:
	@cargo check

doc:
	@cargo doc --open                
"""
			)
		case "python":
			open("makefile", "w").write(
"""
all:
	python3 ./main.py
"""
			)
		
		case "remove":
			os.remove("makefile")
   
		case other:
			print(f"No makefile forund for language {other}")
			sys.exit(1)
   

else:
	print(
		""" Usage: pass the language as an argument to create a makefile for that language. """
	)
